[2022-07-12 21:31:53,173] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.format_to_parquet_task scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 21:31:53,192] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_project_dag-12.format_to_parquet_task scheduled__2022-07-11T00:00:00+00:00 [queued]>
[2022-07-12 21:31:53,193] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 21:31:53,193] {taskinstance.py:1239} INFO - Starting attempt 8 of 9
[2022-07-12 21:31:53,193] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-12 21:31:53,215] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_to_parquet_task> on 2022-07-11 00:00:00+00:00
[2022-07-12 21:31:53,224] {standard_task_runner.py:52} INFO - Started process 4059 to run task
[2022-07-12 21:31:53,234] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_project_dag-12', 'format_to_parquet_task', 'scheduled__2022-07-11T00:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmp4m9ww5l1', '--error-file', '/tmp/tmp_lxp248i']
[2022-07-12 21:31:53,236] {standard_task_runner.py:77} INFO - Job 71: Subtask format_to_parquet_task
[2022-07-12 21:31:53,327] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_project_dag-12.format_to_parquet_task scheduled__2022-07-11T00:00:00+00:00 [running]> on host b7c97f870ea6
[2022-07-12 21:31:53,407] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_project_dag-12
AIRFLOW_CTX_TASK_ID=format_to_parquet_task
AIRFLOW_CTX_EXECUTION_DATE=2022-07-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-11T00:00:00+00:00
[2022-07-12 21:31:53,408] {logging_mixin.py:109} INFO - /opt/***/mashlyn/online-retail-ii-uci/online-retail-ii-uci.zip
[2022-07-12 21:31:53,409] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_to_gcs.py", line 50, in format_to_parquet
    with zipfile.ZipFile(src_file,"r") as zip_ref:
  File "/usr/local/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mashlyn/online-retail-ii-uci/online-retail-ii-uci.zip'
[2022-07-12 21:31:53,430] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_project_dag-12, task_id=format_to_parquet_task, execution_date=20220711T000000, start_date=20220712T213153, end_date=20220712T213153
[2022-07-12 21:31:53,447] {standard_task_runner.py:92} ERROR - Failed to execute job 71 for task format_to_parquet_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_to_gcs.py", line 50, in format_to_parquet
    with zipfile.ZipFile(src_file,"r") as zip_ref:
  File "/usr/local/lib/python3.7/zipfile.py", line 1240, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/mashlyn/online-retail-ii-uci/online-retail-ii-uci.zip'
[2022-07-12 21:31:53,483] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-12 21:31:53,534] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
